### ISSUE TITLE
EventID qualifiers are throwing off ID inclusion/exclusion

### ISSUE THREAD

**Issue by mark-hallman** [EricZimmerman/evtx#11]
In the process of creating evtxcmd maps I found this 
`<EventID Qualifiers="32768">4105</EventID>`  
when I searched for 4105.  I normally search for `<EventID>4105</EventID>`.     evtxecmd does not see this string as an event id 410.  I used --inc 4105 in the cli.  

Is this expected behavior?

Logging this without the example files just so it does not slip through the cracks.  I will get you a sample file(s).

-Mark

**Comment by EricZimmerman** [comment]
what log is this from? like, romanoff, security, or ?

ill try to track it down but if you have a sample file, perfect.

**Comment by EricZimmerman** [comment]
hmm, in nromanoff new data, application log, you see things like this:

<Event>
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-09-06 06:02:06.5441053" />
    <EventRecordID>269649</EventRecordID>
    <Channel>Application</Channel>
    <Computer>base-rd-01.shieldbase.lan</Computer>
    <Security />
  </System>
  <EventData>
    <Data>0, WindowsUpdateFailure3, Not available, 0, 10.0.16299.98, 80240437, 00000000-0000-0000-0000-000000000000, Scan, 0, 0, 0, Update;taskhostw, {855E8A7C-ECB4-4CA3-B045-1DFA50104289}, 0, 
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER339F.tmp.WERInternalMetadata.xml, C:\ProgramData\Microsoft\Windows\WER\ReportQueue\NonCritical_10.0.16299.98_d127d0c9d9253bdcb4e9f182ac69fab59f08c0_00000000_09d9dd50, 0, a5fbe375-e923-43f6-a7ff-4913c2b9550d, 524388</Data>
    <Binary></Binary>
  </EventData>
</Event>


without --exc, i get Records included: 20,134 including 17506 1001 eventIDs

if i do --exc 1001, i get back Records included: 2,628 Errors: 0 Events dropped: 17,506

--inc 1001 works the same:

Records included: 17,506 Errors: 0 Events dropped: 2,628

Metrics (including dropped events)
Event Id        Count
1001            17,506

this is with v0.5.0.0, so please verify your version and let me know how to reproduce this.

**Comment by mark-hallman** [comment]
Eric,

I have just run through these tests again.  I must have been mistaken about the `--inc` not finding the event ID when the `<EventID Qualifiers=`  string precedes the actual event ID.  

Here is the event log samples of what I was looking at in case you want to take a look yourself. You may not have these evtx's 

The condition I thought I was seeing was was found in two event logs from the SRL data (base-wkstn-05-triage, base-wkstn-06-triage).  base-wkstn-05-triage has several instances of the string.  They are all entries for the Application.evtx

Here is a link to the following:

1. The two Application.evtx logs that have the condition (base-wkstn-05-triage, base-wkstn-06-triage)
2. The xml created by evtxecmd that I was using to create the maps.

-Mark

files_for_evtxecmd.7z
Password:  sent via Slack
https://sansorg.egnyte.com/dl/wkNFrYlYCr

**Comment by mark-hallman** [comment]
Closing Issue.  I can not reproduce.
