### ISSUE TITLE
.NET 5 support

### ISSUE THREAD

**Issue by Eran-YT** [EricZimmerman/evtx#134]
**EvtxECmd version**
Latest

**Is your feature request related to a problem? Please describe.**
I wanted to use the library in .NET 5, but it only supports .NET Framework 4

**Describe the solution you'd like**
.NET 5 support & nuget package for it

**Comment by EricZimmerman** [comment]
why not mention this from the beginning?

**Comment by EricZimmerman** [comment]
its pushed
