### ISSUE TITLE
Start date and End date switches do not work correctly

### ISSUE THREAD

**Issue by beyefendi** [EricZimmerman/evtx#16]
EvtxECmd.exe -f ..\evtx\Application.evtx -sd 2016-08-16 12:54:00.0000000 -ed 2016-08-16 14:50:00.0000000 --xml evtx-app-time --debug

evtx-app-time contains events from the month July.

[Application.evtx.log](https://github.com/EricZimmerman/evtx/files/3911233/Application.evtx.log)

**Comment by EricZimmerman** [comment]
Yes they do. You just have to put the values and quotes because there's a space between the date and the time

**Comment by beyefendi** [comment]
EvtxECmd.exe -f ..\evtx\Application.evtx -sd '2016-08-16 12:54:00.0000000' -ed '2016-08-16 16:50:00.0000000' --xml evtx-app-time

Both single quote and double quote produce same wrong results.

**Comment by EricZimmerman** [comment]
drop all the extra 0s. they arent needed

next, use two dashes as all long options require

EvtxECmd.exe -f ..\evtx\Application.evtx --sd '2016-08-16 12:54:00' --ed '2016-08-16 16:50:00' --xml evtx-app-time

**Comment by beyefendi** [comment]
Summary
double quote does not work
sd and ed switches require two dashes
It is worth to document (in help).
Thank you.

**Comment by EricZimmerman** [comment]
any string with spaces always needs quotes

the single vs double dash thing is documented at the bottom of all my programs in the console help
