### ISSUE TITLE
event parser

### ISSUE THREAD

**Issue by j2013t2013** [EricZimmerman/evtx#22]
hi, trying to run it on security.etvx and get an error:
unhandled exception: system.missingmethodexception: method not found systrem.array.empty
at evtx.eventlogmapvalidator..ctor
at evtx.eventlog.loadmaps(string mappath) in d:\code\evtx\evtx\eventlog.cs:line 133

**Comment by EricZimmerman** [comment]
this is your machine not having .net 4.6 or newer, as outlined on the download page.

update and try again
