### ISSUE TITLE
Pass event ID ranges

### ISSUE THREAD

**Issue by gregkutzbach** [EricZimmerman/evtx#230]
**EvtxECmd version**
The version of EvtxECmd you are currently using
1.5.0.0

**Is your feature request related to a problem? Please describe.**
Sometimes I want to look at 100 or so event ID's. I don't want to take the time to make a list. It would be much faster to say 700-800 instead of 700,701,702,...,800

**Describe the solution you'd like**
Allow event ID ranges to be added inline with the normal event id's

1,2,3,70-90,105,106,200-210

**Describe alternatives you've considered**
powershell script, creating my list in excel and copying it in

**Additional context**

**Comment by EricZimmerman** [comment]
This is done in the code. @AndrewRathbun will test and I'll release an updated binary after that.

**Comment by AndrewRathbun** [comment]
> This is done in the code. @AndrewRathbun will test and I'll release an updated binary after that. 

It works!

**Comment by EricZimmerman** [comment]
Will release in an hour or so. No version bump
